---
abstract: 'Apache2::REST::Response Writer for atom feeds, http://tools.ietf.org/html/rfc4287'
author:
  - 'Wes Young, <wes@barely3am.com>'
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CIF-WebAPI-Writer-atom
no_index:
  directory:
    - inc
    - t
requires:
  CIF::WebAPI: 0.01_01
  XML::Atom: 0.28
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_01
